### PR TITLE
Fix relative path in scanner script

### LINKED ISSUE #195: [Error] Waterfall Generator Script Bad Relative Path
The `scripts/testing/generate_waterfall.sh` script has a relative path referenced in it that fails the waterfall generation when run from a different (non local) directory. This needs to be fixed.

### PR DESCRIPTION
**Pull request by Cirromulus**
This PR adds correct path handling and a bit moire error tracking.

### CODE REVIEW

File: scripts/testing/scan_for.sh [hunk 1]
```diff
@@ -15,8 +15,16 @@ outfile=timed_scan_$(date  +"%d.%m.%y-%H.%M").csv.gz
 
 echo "
 $(tput setaf 2)
-        Scanning for $duration, output file is $outfile .
+        Scanning for $duration, expect a $outfile.png in $(pwd) afterwards.
 $(tput sgr0)"
 
 $scriptpath/start_scanning.sh $outfile
-nohup bash -c "sleep $duration; $scriptpath/stop_and_finalize_scanning.sh $outfile" 2> /dev/null &
+if ! pidof rtl_power >/dev/null ; then
```
Comment (jekhokie) [inline scripts/testing/scan_for.sh:22]: You might want to check for both `rtl_power` and `rtl_fm` given the latter is what is actually run by the capture scripts?

**Review by jekhokie — CHANGES_REQUESTED** [review]

File: scripts/testing/scan_for.sh (hunk 1 above)
Comment (Cirromulus) [reply scripts/testing/scan_for.sh:22]: This is a check if rtl_power succeeded to grab a rtl-sdr.
So it does not matter if the sdr is currently taken by any of the rtl_* commands

File: scripts/testing/scan_for.sh [hunk 2]
```diff
@@ -15,8 +15,16 @@ outfile=timed_scan_$(date  +"%d.%m.%y-%H.%M").csv.gz
 
 echo "
 $(tput setaf 2)
-        Scanning for $duration, output file is $outfile .
+        Scanning for $duration, expect a $outfile.png in $(pwd) afterwards.
 $(tput sgr0)"
 
 $scriptpath/start_scanning.sh $outfile
-nohup bash -c "sleep $duration; $scriptpath/stop_and_finalize_scanning.sh $outfile" 2> /dev/null &
```
Comment (Cirromulus) [inline scripts/testing/scan_for.sh:22]: There was actually another bug hidden, because
1. `2>` just redirects stderr, not stdout
2. the redirection happens for the finalizing script, not for nohup itself

File: scripts/testing/scan_for.sh (hunk 1 above)
Comment (jekhokie) [reply scripts/testing/scan_for.sh:22]: Oh right, nice - sorry about that, LGTM.
